### ISSUE TITLE
Using with dbt_utils 0.3.0

### ISSUE THREAD

**Issue by edbizarro** [dbt-labs/dbt-audit-helper#16]
With my deps as follow

```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.3.0
  - package: fishtown-analytics/audit_helper
    version: 0.0.5
```
I'm getting this error: 

```
 dkc exec dbt dbt deps
Running with dbt=0.16.0
Encountered an error:
Version error for package fishtown-analytics/dbt_utils: Could not find a satisfactory version from options: ['=0.3.0', '>=0.1.24', '<0.3.0']
```

Any plans to support dbt_utils >= 0.3.0 ?

Thanks!
