### ISSUE TITLE
Required version of dbt for 'dbt_utils': ['>=0.20.0', '<0.21.0'] but latest stable version of dbt is 0.19.2

### ISSUE THREAD

**Issue by TeddyCr** [dbt-labs/dbt-audit-helper#37]
### Describe the bug
In `dbt-audit-helper` the `dbt-utils` version is [>=0.7.0,<0.8.0], though, it appears this version of dbt_utils does not support any version of dbt less than 0.20.0, though the latest stable version of dbt is 0.19.2

### Steps to reproduce
Install `audit_helper` create a model and compile it.

```yml
# package.yml
packages:
    - package: dbt-labs/dbt_utils
      version: 0.7.0
    - package: dbt-labs/audit_helper
      version: 0.4.0
```

```shell
dbt deps
```

```shell
dbt compile -m. path.to.my.audit_helper.model
```

### Expected results
Compiled query in `target/`

### Actual results
```
Running with dbt=0.18.1
Encountered an error:
Runtime Error
  Failed to read package: Runtime Error
    This version of dbt is not supported with the 'dbt_utils' package.
      Installed version of dbt: =0.18.1
      Required version of dbt for 'dbt_utils': ['>=0.20.0', '<0.21.0']
    Check the requirements for the 'dbt_utils' package, or run dbt again with --no-version-check
```
Running with `--no-version-check` throws a different error
```
Compilation Error in model <my_models> (path/to/my/model.sql)
  In adapter.dispatch, got a string packages argument ("dbt_utils"), but packages should be None or a list.
```

### System information
```yml
# package.yml
packages:
    - package: dbt-labs/dbt_utils
      version: 0.7.0
    - package: dbt-labs/audit_helper
      version: 0.4.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.19.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1
```

**The operating system you're using:** MacOs 11.4

**The output of `python --version`:** python 3.8.3

### Are you interested in contributing the fix?
For sure.
