### ISSUE TITLE
version dependency with dbt_utils conflict

### ISSUE THREAD

**Issue by AdilYakubov** [dbt-labs/dbt-audit-helper#53]
### Describe the bug
installation/upgrade with together with dbt-util is conflicting

### Steps to reproduce

```yml
packages:
  - package: dbt-labs/audit_helper
    version: [">=0.5.0", "<0.6.0"]

  - package: dbt-labs/dbt_utils
    version: [">=0.9.0", "<0.10.0"]

```

### Expected results
dbt-audit-helper working with latest dbt-utils

### Actual results
dbt-utils upgrade is failing

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.1
  - latest:    1.2.1 - Up to date!

Plugins:
  - bigquery: 1.2.0 - Up to date!
```

**The operating system you're using:**
using Fedora Linux 36

**The output of `python --version`:**
Python 3.10.6

### Are you interested in contributing the fix?
Yes, can create a PR with a version bump
