### ISSUE TITLE
Version error for package dbt-lab--dbt_utils 

### ISSUE THREAD

**Issue by normwarren** [dbt-labs/dbt-audit-helper#59]
### Describe the bug

I get a version error for package dbt-lab--dbt_utils, while attempting to install dbt-audit-helper. 

### Steps to reproduce

1. Add dbt-labs/audit_helper to packages.yml
2. Run dbt deps

### Expected results

audit_helper package in installed. 

### Actual results

Get the following error: 
```
23:41:31  Running with dbt=1.3.1
23:41:33  Encountered an error:
Version error for package dbt-labs/dbt_utils: Could not find a satisfactory version from options: ['>=0.8.0', '<1.0.0', '>=0.8.0', '<2.0.0', '>=0.9.0', '<2.0.0', '>=0.8.0', '<0.9.0']
```

--->

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: fivetran/stripe
    version: [">=0.7.3"]
  - package: fivetran/hubspot
    version: [">=0.5.0", "<0.8.0"]
  - package: elementary-data/elementary
    version: [">=0.5.0", "<0.8.0"]
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0", "<1.0.0"]

  # - package: dbt-labs/audit_helper
  #   version: [">=0.6.0", "<0.9.0"]
```
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt=1.3.1
```

**The operating system you're using:**
Montery

**The output of `python --version`:**
Python 3.10.3
